### ISSUE TITLE
issue with recursion

### ISSUE THREAD

**Issue by ghost** [chenho2000/MAT406-Program#1]
Hi there, 

I think there might be an issue with the recursion strategy in your code: as you remove rows (and columns) the shape of the matrix changes; once recursion finishes and you start to return back to the previously called functions, you are still iterating on the old size of the matrix; this is incorrect as far as I can see.  

Personally, I don't see why you should recursion here, I'd iterate on removing_dominated_strategies(m, text) until it does not find anything to dominate and then stop the loop…

**Comment by chenho2000** [comment]
Hello Professor Jacopo:
Thank you so much for the advice!! 
Yes, using loop will definitely work as well and it’s an awesome idea. So the issue is my function will still loop the old size matrix in the previously called function after everything is done right? I think it won’t actually return back to the previously called function's loop. Since in the previously called function it’s already in the return statement. (So the end of the function). It will send the new matrix to the previously called function and return it directly. No more loop. I used recursion is basically because it's the first thing that comes up to my mind. I can definitely make a loop version also. 🙂
Here's some testing that shows it won't go back to the previously called function and continue looping. 
I added some print statements in the loop so every time it continues looping, I will know which columns/rows the function currently checking.
<img width="530" alt="image" src="https://user-images.githubusercontent.com/60719036/143136426-e2848e5b-d7fc-43bc-bad3-dccf93a371a8.png">
Then there's a test case: (it's one example from the assignment and my function's output is correct)
(This is the first half of the print statement)
![image](https://user-images.githubusercontent.com/60719036/143136463-ad9bfd79-0ae2-4e5e-92f5-0985087e0b83.png)
![image](https://user-images.githubusercontent.com/60719036/143136480-47aea440-ff9a-4a73-959a-307ec61e3e96.png)
In this test case, the function will loop till it finds a dominated column/row and deletes it. And continue searching in the new matrix (smaller size matrix). At the end of the process, it just goes over the last 2*2 matrix. Checked there's no more dominated column/rows and end the process. So the rest of the loop from the previously called function will not continue. And it will not iterate on the old size of the matrix. If you wish to take a look at this test in notebooks I can push it to GitHub 🙂.
Thank you so much for the advice. I'm still working on the mixed dominated strategy but since it's almost exam period so I have to finish other assignments first, but I will definitely go back to it! If there are any other issues please let me know, I can explain through email or during office hours.
Thanks again!
Hope you have a nice day
Hongyu Chen

**Comment by ghost** [comment]
Thanks, it looks ok!
